### ISSUE TITLE
PF2e Enemies not set to defeated.

### ISSUE THREAD

**Issue by SinBroom** [BoltsJ/lancer-initiative#22] opened 2022-02-18 09:51 UTC
This happens when playing pf2e with the module enabled. 
In combat when an enemy's HP is reduced to 0 the enemy is not set to "defeated" with the skull and such.

Having spoken to Drental about this, he is more knowledgeable about the PF2e system and said it is because of something to do with "CombatantPF2e"

I hope this helps :)

**Comment by BoltsJ** [comment] 2022-02-20 16:19
If those functions are tied to a custom combatant class, then this module won't be compatible with that functionality.

**Comment by Lewisdc** [comment] 2022-02-23 18:54
Is there any possibility that the module could use PF2e combatant when the world is PF2e?
I don't really understand how this all works, sorry.

**Comment by BoltsJ** [comment] 2022-03-05 22:15
It would only be possible if the Pathfinder combatant class extended `LancerCombatant` from this module or otherwise had a reimplementation of the necessary interface.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BoltsJ** [comment] 2022-03-21 18:52
I'll look into a shim module to make the two work together. I can't guarantee anything tho.

**Comment by SinBroom** [comment] 2022-03-21 23:27
That is awesome and super cool to hear.
I understand you can't promise success but that sounds really cool.
If there is anything I can do to help please let me know :)
And good luck! <3

**Comment by CarlosFdez** [comment] 2022-03-22 00:18
I haven't dug into the source code, but I saw this linked in the pf2e discord. Would it to be possible instead to extend the pf2e combatant (or rather....any system overriden combatant) with the lancer one? The PF2e combatant class is in the config (CONFIG.Combatant.documentClass), and its expected that any system specific subclass would be registered there as well.

**Comment by SinBroom** [comment] 2022-03-22 02:12
@CarlosFdez 

I think the best outcome in my mind would be for all the functionality of the Pathfinder 2e combatants like persistent damage and effects running out and such to work with the Lancer Initiative tracking UI.
How would that be approached?

**Comment by CarlosFdez** [comment] 2022-03-22 07:27
So persistent damage is not handled by the system, but actually by a module of mine (though eventually it will be implemented in the system itself). It keys off the "pf2e.endTurn" event, which in turn is fired by either EncounterPF2e#nextTurn() or when EncounterPF2e is deleted. So long as EncounterPF2e's nextTurn() implementation is executed, it should work fine. 

This is I believe the system's implementation of the Combat class, which is in CONFIG.Combat.documentClass.

**Comment by BoltsJ** [comment] 2022-03-25 15:57
Subclassing `CONFIG.Combat.documentClass` is a complete non-starter as it would require radically redesigning how this module initializes. Even if I were inclined to make such a change, I don't have the time. 

I would have to move the creation of the classes into an `init` hook, then move the assignment of those new classes into `setup`. I then would need to recreate the combats, since by setup, the world collections are already initialized. 

Ultimately, I'm not sure what the pf2e versions of combat and combatant are doing that utilizing the hooks available on the core implementations we're too limited to do.

**Comment by SinBroom** [comment] 2022-03-26 19:51
> Subclassing `CONFIG.Combat.documentClass` is a complete non-starter as it would require radically redesigning how this module initializes. Even if I were inclined to make such a change, I don't have the time. 
> 
> I would have to move the creation of the classes into an `init` hook, then move the assignment of those new classes into `setup`. I then would need to recreate the combats, since by setup, the world collections are already initialized. 
> 
> Ultimately, I'm not sure what the pf2e versions of combat and combatant are doing that necessitates a full subclass. All of the functionality I observed in my testing of the system could be easily done by hooking `updateCombat`. 

The method Carlos suggested wouldn't work then?

**Comment by CarlosFdez** [comment] 2022-03-26 20:31
Unfortunately we're unlikely to change that since its the recommended way to do it by Foundry. I'm surprised you have to move the assignment to setup if you do that instead of keeping it in init. It should be possible to create the Lancer class in init and then assign it to CONFIG immediately via doing something akin to `CONFIG.Combat.documentClass = createLancerCombat(CONFIG.Combat.documentClass)` or something of that sort, so if you're unable to do that I'm assuming there's probably some other thing causing this to not work.

Only other thought is something like a decorator.

**Comment by CarlosFdez** [comment] 2022-03-30 06:18
For the PF2e master branch, the CONFIG properties are now set before the init hook even runs, so now no special effort of subclassing and assigning at the same time needs to be done. You should be able to subclass CONFIG.Combat.documentClass without repercussions.

**Comment by SinBroom** [comment] 2022-03-30 17:03
That's awesome news, right? :D

**Comment by BoltsJ** [comment] 2022-03-30 17:09
I will not subclass `CONFIG.Combat.documentClass`. There's too much potential for conflicts with other systems in doing that, and the code for the documents is directly included in the lancer system, so I'm not willing to change the API in such a way.

Plus, it wouldn't work anyway, since `nextTurn`, `previousTurn`, `nextRound` and `previousRound` don't (and can't) inherit the superclass's implementation. Turns aren't traversed linearly, so the `nextTurn` method is overridden to set the turn to `null`. `previousTurn` is iirc a NOP currently, since I don't save turn history (it is a very low priority TODO.) In general, if a method's stock implementation changes the turn, it's necessary to not call the base method to avoid activation the incorrect combatant (i.e. any combatant at all on new rounds). 

Also, if I change the documents to subclass from `CONFIG`, that makes this module pf2e *only*. I was planning to create a companion module that used `libwrapper` to insert the necessary methods back on, and to use hooks to reimpliment the rest, but since pf2e doesn't make any of the documents available in `game.pf2e`, I'm still looking into the best way to do that.

To be absolutely clear: I will not subclass from the `CONFIG` object.

**Comment by CarlosFdez** [comment] 2022-03-30 23:45
I suspect you are misunderstanding the suggestion and conversation. CONFIG.Combat.documentClass is a foundry included property, and most systems do not touch it and will default to the classes you are subclassing. The system that it makes it pf2e only is incorrect.

These are, for example, the values in a D&D5e world:
![image](https://user-images.githubusercontent.com/1286721/160948601-09de85e6-20f7-47e5-aae8-3bf0a5494141.png)

These are classes you're already subclassing, leading to no change in behavior.

That said, whether or not it will work or not is a separate discussion altogether. I do not know what other system changes the combat class and in what way either. But I know for sure no change will happen for D&D 5e.

**Closed** 2022-03-30 23:49 UTC
Labels: module-conflict, ingored template

**Comment by CarlosFdez** [comment] 2022-03-31 19:27
Feel free to block me for this one final reply.

I don't particularly mind what you do or don't. If you don't like it as a solution, I am fine with that as well. I merely stated the options available and the usual solutions, but that didn't prevent any other options as well. It also didn't prevent the option of "I'd rather not". That is your prerogative. Closing the issue is fine as well.

That said, I was not representing the pf2e community. I came here as a single dev, with some codebase knowledge, who gave a suggestion. Please do not assume this was a PF2e community involvement in any way. A dev without any personal interest in the module, mind you. The update to the master branch wasn't by me, but by someone else who is a busy body who likes solving problems. If you wish to burn every single bridge for code contributions from other people, that will not harm me, but I implore you to rise above that. At the end of the day, everyone here is a volunteer.

That said, I do find it interesting that 5e has a secondary place they put their overriden entities in. They do override CONFIG.Actor.documentClass, but it seems they also override that as well. I was not aware of that. Perhaps it predated the official solution.
