### ISSUE TITLE
Star Wars FFG - Can't Roll Initiative

### ISSUE THREAD

**Issue by Warrior-Elite** [BoltsJ/lancer-initiative#23] opened 2022-03-03 03:10 UTC
<details>
<summary>Basic information</summary>
 - Lancer Initiative version: 23
 - Foundry VTT version: 9.251
 - Game system and version: Star Wars FFG 1.72
</details>

Can't roll initiative. Getting this error message on Console:
```
Uncaught (in promise) Error: Unresolved StringTerm Cool requested for evaluation
[Detected 1 package: system:starwarsffg]
at StringTerm.evaluate (foundry.js:9192:11)
    at roll.js:129:23
    at Array.map (<anonymous>)
    at RollFFG.evaluate (roll.js:125:31)
    at LancerCombat.rollInitiative (foundry.js:15721:18)
    at LancerCombat.rollAll (foundry.js:15770:17)
    at LancerCombatTracker._onCombatControl (foundry.js:58672:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:58594:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at HTMLAnchorElement.v.handle (jquery.min.js:2:41048)
```
This is true for individual rolls and the "Roll All" button as well. It doesn't bring up the menu that would normally pop up to choose between the Cool or Vigilance check for roll.

**Expected behavior**
A modal should appear that would normally ask to choose between the Cool or Vigilance check for roll when you roll for initiative.

**Comment by BoltsJ** [comment] 2022-03-05 22:17
Duplicate of #20

**Closed** 2022-03-05 22:17 UTC
Labels: bug
